# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/WorkSpace/project/FPGA/prj_sc2238_v2.0_emmc/prj_sc2238/prj_sc2238.srcs/sources_1/ip/v_tc_0/v_tc_0.xci
# IP: The module: 'v_tc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/FPGA/prj_sc2238_v2.0_emmc/prj_sc2238/prj_sc2238.srcs/sources_1/ip/v_tc_0/v_tc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_tc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_sc2238_v2.0_emmc/prj_sc2238/prj_sc2238.srcs/sources_1/ip/v_tc_0/v_tc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/WorkSpace/project/FPGA/prj_sc2238_v2.0_emmc/prj_sc2238/prj_sc2238.srcs/sources_1/ip/v_tc_0/v_tc_0.xci
# IP: The module: 'v_tc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/FPGA/prj_sc2238_v2.0_emmc/prj_sc2238/prj_sc2238.srcs/sources_1/ip/v_tc_0/v_tc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_sc2238_v2.0_emmc/prj_sc2238/prj_sc2238.srcs/sources_1/ip/v_tc_0/v_tc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
